export const movies = [
  { name: "starwar", id: 0, source: "/starwar.jpg" },
  { name: "marvel", id: 1, source: "/marvel.jpg" },
  { name: "titanic", id: 2, source: "/titanic.png" },
  { name: "flash", id: 3, source: "/speed.jpg" },
  { name: "joker", id: 4, source: "/joker.jpg" },
  { name: "twilight", id: 5, source: "/twilight.jpg" },
  { name: "Tomcruise", id: 6, source: "/tomcruise.jpg" },
  { name: "hobbit", id: 7, source: "/hobbit.jpg" },
  { name: "deadpool", id: 8, source: "/deadpool.png" },
  { name: "intution", id: 9, source: "/horror.jpg" },
  { name: "A quite place", id: 10, source: "/inception.jpg" },
  { name: "matrix", id: 11, source: "/matrix.jpg" },
];
export const availableDates = [
  { id: 0, month: "Jun", day: "Sunday", date: "1st" },
  { id: 1, month: "Aug", day: "Tuesday", date: "15th" },
  { id: 2, month: "Mar", day: "Thursday", date: "8th" },
  { id: 3, month: "Nov", day: "Monday", date: "21st" },
  { id: 4, month: "Apr", day: "Friday", date: "16th" },
  { id: 5, month: "Sep", day: "Wednesday", date: "30th" },
  { id: 6, month: "Dec", day: "Saturday", date: "12th" },
  { id: 7, month: "Jan", day: "Tuesday", date: "4th" },
  { id: 8, month: "May", day: "Thursday", date: "27th" },
  { id: 9, month: "Oct", day: "Sunday", date: "23rd" },
];
